theme = "github_dark"

[keys.insert]
j = { j = "normal_mode"}

[keys.normal]
C-s = ":write"
C-h  = "jump_view_left"
C-l= "jump_view_right"
V = ["extend_to_line_bounds", "select_mode"]
G = "goto_file_end"
H = "goto_line_start"
L = "goto_line_end"
"|" = "vsplit"
"\\" = "hsplit"

[keys.normal.space]
e = {w = ":write", c = ":bc", x = ":bco", l = ":toggle lsp.display-inlay-hints" }
q = ":quit"

[keys.normal."+"]
f = ":format"
w = ":toggle whitespace.render all"
W = ":set whitespace.render none"
s = ":toggle soft-wrap.enable"

[keys.normal."["]
b = "goto_previous_buffer"

[keys.normal."]"]
b = "goto_next_buffer"

[keys.normal."C-w"]
"|" = "vsplit"
"/" = "hsplit"

[keys.normal.space.f]
f = "file_picker_in_current_directory"
F = "file_picker"
b = "file_picker_in_current_buffer_directory"
"." = ":toggle-option file-picker.git-ignore"
g = "global_search"
e = "file_explorer"
r = ":reload-all"
c = ":config-reload"
x = ":reset-diff-change"
w = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"
d = [":vsplit-new", ":lang diff", ":insert-output git diff"]



[editor]
mouse = true
completion-replace = true
trim-trailing-whitespace = true
end-of-line-diagnostics = "hint"
default-yank-register = "+"
clipboard-provider = "pasteboard"
bufferline = "multiple"
true-color = true

[editor.auto-save]
focus-lost  = true
after-delay.enable = true
after-delay.timeout = 300000

[editor.statusline]
left = [
  "mode",
  "spinner",
  "version-control",
  "spacer",
  "separator",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
]
center = []
right = [
  "diagnostics",
  "workspace-diagnostics",
  "position",
  "total-line-numbers",
  "position-percentage",
  "file-encoding",
  "file-line-ending",
  "file-type",
  "register",
  "selections",
]
separator = "│"
