# プレフィックスキーを Ctrl-Space に変更
set -g prefix C-space
unbind C-b

# pane resize (prefix + H/J/K/L)
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# 分割時にカレントパスを引き継ぐ
bind % split-window -h -c '#{pane_current_path}'
bind '"' split-window -v -c '#{pane_current_path}'

# yazi をポップアップで起動
bind-key y display-popup -d '#{pane_current_path}' -x R -h 95% -w 95% -E 'tmux new-session yazi \; set status off'

# lazygit をポップアップで起動
bind-key g popup -E -w 95% -h 95% -d '#{pane_current_path}' lazygit
